name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Users/macos/Downloads/Xcode.app
      
    - name: Build and Test
      run: xcodebuild clean build test -workspace CoreDataCRUD.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

